services:
  db:
    image: postgres
    container_name: postgres
    volumes: 
      - rebase-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    networks:
      - base

  app:
    image: ruby
    container_name: app
    command: bash -c "bundle install && ruby server.rb"
    ports:
      - 3000:3000
    depends_on:
      - db
      - sidekiq
    working_dir: /app
    networks:
      - base
    volumes:
      - ./:/app
      - gems:/usr/local/bundle
    environment:
      APP_ENV: development
      DB: db
      REDIS_URL: redis://redis:6379

  redis:
    image: redis
    container_name: redis
    networks:
      - base

  sidekiq:
    image: ruby
    container_name: sidekiq
    command: bash -c "bundle install && bundle exec sidekiq -r './data_worker.rb'"
    working_dir: /app
    networks:
      - base
    volumes:
      - ./:/app
      - gems:/usr/local/bundle
    depends_on:
      - redis
    environment:
      APP_ENV: development
      DB: db
      REDIS_URL: redis://redis:6379

  tests:
    image: ruby
    container_name: tests
    command: bash -c "bundle install && ruby server.rb"
    working_dir: /app
    networks:
      - base
    volumes:
      - ./:/app
      - gems:/usr/local/bundle
      - .tests:/tests
    depends_on:
      - tests-db
      - sidekiq
    environment:
      APP_ENV: test 
      DB: tests-db
  
  tests-db:
    image: postgres
    container_name: tests-postgres
    volumes: 
      - test-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    networks:
      - base

networks:
  base:
volumes:
  gems:
  rebase-db:
  test-db: