#!/bin/bash

docker run \
  --rm \
  --network base \
  -w /app \
  -v $(pwd):/app \
  -p 3000:3000 \
  ruby \
  bash -c "gem install rack sinatra puma pg && ruby medical_record.rb && ruby server.rb"
