#!/bin/bash

docker run \
  --rm \
  --name app \
  --network base \
  -w /app \
  -v $(pwd):/app \
  -v gems:/usr/local/bundle \
  -p 3000:3000 \
  ruby \
  bash -c "bundle install && ruby server.rb"
